# Generated by Django 3.0.6 on 2020-10-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
