# Generated by Django 3.0 on 2020-10-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
